- name: Django Action
  # You may pin to the exact commit or the version.
  # uses: noah-software/django_action@da6e513b3afbad089396b7c1c330909a3a00925f
  uses: noah-software/django_action@v1.1
  with:
    # Commit message of the changed data
    commit_message: # optional, default is Added data schema
    # Path relative to the repository root, where the requirements.txt is located
    pip_path: # optional, default is requirements.txt
    # Output path for the generated data scheme
    output_path: # optional, default is schema.png
    # Path to the folder where manage.py is located
    project_path: # optional, default is ./
